# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  LoggingOptions: '-Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Compile application'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
    mavenOptions: '$(LoggingOptions)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
  env:
      CLIENT_ID: '$(INTERACTIVE_CLIENT_ID)'



- task: Maven@3
  displayName: 'Run tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    mavenOptions: '$(LoggingOptions)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  env:
    KEY_VALUE: '$(VAULT_URL)'
    AZURE_CLIENT_ID: '$(AZURE_ID)'
    AZURE_TENANT_ID: '$(TENANT_ID)'
    AZURE_CLIENT_SECRET: '$(CLIENT_SECRET)'
